/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/trees.glb -o src/app/glb/Trees.jsx -k -K -r public 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Trees(props) {
  const { nodes, materials } = useGLTF("/models/trees.glb");
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh
          name="group1309878107"
          geometry={nodes.group1309878107.geometry}
          material={materials.mat16}
        />
        <mesh
          name="group1735826486"
          geometry={nodes.group1735826486.geometry}
          material={materials.mat17}
        />
        <group name="group1958235271">
          <mesh
            name="mesh1958235271"
            geometry={nodes.mesh1958235271.geometry}
            material={materials.mat19}
          />
          <mesh
            name="mesh1958235271_1"
            geometry={nodes.mesh1958235271_1.geometry}
            material={materials.mat9}
          />
        </group>
        <group name="group720331588">
          <mesh
            name="mesh720331588"
            geometry={nodes.mesh720331588.geometry}
            material={materials.mat10}
          />
          <mesh
            name="mesh720331588_1"
            geometry={nodes.mesh720331588_1.geometry}
            material={materials.mat19}
          />
        </group>
        <group name="group833803046">
          <mesh
            name="mesh833803046"
            geometry={nodes.mesh833803046.geometry}
            material={materials.mat9}
          />
          <mesh
            name="mesh833803046_1"
            geometry={nodes.mesh833803046_1.geometry}
            material={materials.mat20}
          />
        </group>
        <group name="group1145296422">
          <mesh
            name="mesh1145296422"
            geometry={nodes.mesh1145296422.geometry}
            material={materials.mat20}
          />
          <mesh
            name="mesh1145296422_1"
            geometry={nodes.mesh1145296422_1.geometry}
            material={materials.mat9}
          />
        </group>
        <group name="group2112331936">
          <mesh
            name="mesh2112331936"
            geometry={nodes.mesh2112331936.geometry}
            material={materials.mat20}
          />
          <mesh
            name="mesh2112331936_1"
            geometry={nodes.mesh2112331936_1.geometry}
            material={materials.mat11}
          />
        </group>
        <group name="group373735999">
          <mesh
            name="mesh373735999"
            geometry={nodes.mesh373735999.geometry}
            material={materials.mat19}
          />
          <mesh
            name="mesh373735999_1"
            geometry={nodes.mesh373735999_1.geometry}
            material={materials.mat9}
          />
        </group>
        <group name="group1114869579">
          <mesh
            name="mesh1114869579"
            geometry={nodes.mesh1114869579.geometry}
            material={materials.mat19}
          />
          <mesh
            name="mesh1114869579_1"
            geometry={nodes.mesh1114869579_1.geometry}
            material={materials.mat10}
          />
        </group>
        <group name="group1932686607">
          <mesh
            name="mesh1932686607"
            geometry={nodes.mesh1932686607.geometry}
            material={materials.mat9}
          />
          <mesh
            name="mesh1932686607_1"
            geometry={nodes.mesh1932686607_1.geometry}
            material={materials.mat19}
          />
        </group>
        <group name="group546125134">
          <mesh
            name="mesh546125134"
            geometry={nodes.mesh546125134.geometry}
            material={materials.mat19}
          />
          <mesh
            name="mesh546125134_1"
            geometry={nodes.mesh546125134_1.geometry}
            material={materials.mat10}
          />
        </group>
        <group name="group100681590">
          <mesh
            name="mesh100681590"
            geometry={nodes.mesh100681590.geometry}
            material={materials.mat19}
          />
          <mesh
            name="mesh100681590_1"
            geometry={nodes.mesh100681590_1.geometry}
            material={materials.mat11}
          />
        </group>
        <group name="group2102696020">
          <mesh
            name="mesh2102696020"
            geometry={nodes.mesh2102696020.geometry}
            material={materials.mat10}
          />
          <mesh
            name="mesh2102696020_1"
            geometry={nodes.mesh2102696020_1.geometry}
            material={materials.mat20}
          />
        </group>
        <mesh
          name="group601634601"
          geometry={nodes.group601634601.geometry}
          material={materials.mat21}
        />
        <mesh
          name="group1795976569"
          geometry={nodes.group1795976569.geometry}
          material={materials.mat21}
        />
        <group name="group1206298165">
          <mesh
            name="mesh1206298165"
            geometry={nodes.mesh1206298165.geometry}
            material={materials.mat11}
          />
          <mesh
            name="mesh1206298165_1"
            geometry={nodes.mesh1206298165_1.geometry}
            material={materials.mat19}
          />
        </group>
        <group name="group1610579876">
          <mesh
            name="mesh1610579876"
            geometry={nodes.mesh1610579876.geometry}
            material={materials.mat9}
          />
          <mesh
            name="mesh1610579876_1"
            geometry={nodes.mesh1610579876_1.geometry}
            material={materials.mat20}
          />
        </group>
        <group name="group874600975">
          <mesh
            name="mesh874600975"
            geometry={nodes.mesh874600975.geometry}
            material={materials.mat9}
          />
          <mesh
            name="mesh874600975_1"
            geometry={nodes.mesh874600975_1.geometry}
            material={materials.mat10}
          />
          <mesh
            name="mesh874600975_2"
            geometry={nodes.mesh874600975_2.geometry}
            material={materials.mat19}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/trees.glb");
