const validateLicense = require("validate-npm-package-license");

let getColor = (obj) => {
    if (obj.classList.toString().indexOf('red') >= 0) {
        return 'R';

    } else if (obj.classList.toString().indexOf('black') >= 0) {
        return 'B';
    } else {
        console.log(obj.classList)

        return 'G';
    }
}

valores = '';
document.querySelectorAll('.classic-statistics-container--2-9Fx [data-role^=number]').forEach(obj => {
    const color = getColor(obj);
    valores += color;
});


console.log(valores)

Color predominante: Negro
BRRRBRRGBRBBRRRRBRGRRRRBBBRBBBRRBBBRRRRRRRBBRRBRRRBBBBRRRRBRRRBRRBRRBBBRRBBBBRRBBBBRBRBRBRRRBBRBBRRRRRBRBBBRRRBBBRBBBRBRBRBBRRRBRRRRRBRRRBRGRRRGRBRBRBBBBRRBBBRBRBBBBBBBRBBBGBRBRRBRBRRBRRRRBBBRRRRRBBBBRRBBBRRRRRRBBBBGBRBBRRRBBBRBRRBRBRBBRRBRGRBBBRBRBBBRBGBGGRRBBRRRBRGRRBRGRRRBBBBBRBRBRRRRBBBBBBRBBBBBRBGBRRBRBRBRRRBRBRBBRRBRBBRRBRRRBBBBRRRRRRBRBBBRRBBRRRBBRRRBBBRRBBRBBRRBRRBRRBBBRBBBBRRRBRBRRRBRRRRRRBBBRRBBBRRRBBBBBBRRRBBBRBRRRRRBBRBRRRBGBRRRBRRBBBRBRBRRBRRGRBRBRBBBBRRRRRBBRRRBRBRBBRR
Color predominante: Negro
BRBBRBBBRBBRBRBRBRRBRBBBRRRRRRBRBBRRRBRGBBRBRRBBRBBBRBRRBBBRBBRRRBBBBRBBRRBBBRRBBRRBBBRBBBRBBBRBRRRBBRBRRRRRBRBRRBRGBBRRBRRBRRBRRRBRRBBRBRRBRBBRRBRRBRRBBRBBBBBBBRRRBBRRRBRBBRBBRBBBRBBRRRRBRBBBBRBRBRBBBBRBRBRBRRRRBBRBBBRGBBBBBRRBRRRBRGRBBBRBRRBBRBBBBBBRBBBBRBBRRRBBRRBBRRRRBBRBRBBRGRBRBRRRRRRGBBRRBRBBBBBGRBBRBRRBRRBBRBBRRRBBBBBBRBBBRBRBRBRRBBRRRRRBBRBRRBRRBRBRBBRBBBBBRRRBRBRBBBRRRRRRBRBRRBBBBBRRBRBBBBBRBBRGRRRBRRRBBRBRBRBRBRBGBRBBRBRBBRBRRRBBBBRGRBBRRRBBBRBRBBBBBRRGRBRRBRRBBBRRRBRBBRR
Color predominante: Rojo(La chica dijo que aunque llevaba poco tiempo nunca había tenido una racha tan larga)
BRBBBBBRBBBBRRRRRRRRRRBRBBRBBRRBRRRBRRRBBBRRBBRRRBRBBBRRBBBBRBRRBRBBRBBRBBRBBBBRBRRBBRBBBRRRBBBRBBRRRRBRBRBBRBRBRRBBGRRBBBRBBRRRBRGBRBRBGRBBRRRBRGRRBBRRBBBBBBRRRRRBRRBRBRRRBBRRBBRBBRBBRBRRRRBBBRBBBRBBBBRRRBBRRRBBRRRBBRRRRBRBBRBRRRGRBRRBBBRGRRRBRBRBBBRRRBBRBRRBRGRRBRRRBBRRRRRRBRRBRRBBBBBBRBBBBRBRRRBBRRBBRRRBRRBRRBBRRRBBRRRBRRBBRBRRRBRRBRBRBRBBBBBBBRRBRRBBBBRRBBBBBRRRRBRBBRRRRRBBBBRRBRRBRRRBBBRRBBBRRBRRBBRBBRBRBRBBRBBRRBRRRBRRBRBRRRBRRBBRBRBBRBRBBRBRRBBRBBRBBRRRRRRRBRRBBBBGRBBBRBRRBRB
Color predominante: Negro(máxima racha de negros: 14)
BRRRBBBRBRRRBRRRBRBRBRRBBBRRBBBBBRRBRRRBRRBBBBRRBRRRBRRBBBBBRBGRBBBBRRRBBRRBGRBRRBBBBBGBRBRBRRRBRBBBBRRRBBRRBRRBBBRRRBRRBBRBBRBBRRBBRBRRBRBRBRRBBBRBBRBRBRBRBBRGBBGRRRRRBBRRRBRBBBGBRBRBBBRBBRGBRBRBBGBRBBBRRBBBRBRBRBRRBBRBRRBBBRRBRBRRBRBBRBBBBRRBBRBBBRBRBRRBGRRBRBRBRRRRBBRRRBBRRRBBRRRRRRRRRRRRBBBRRRRBRBRBRBBRBBBBBBRRRBBRBRBBBBRBRBBBBRBGBRBBBBRBBBBRRRRBBRBRRRRRRRBBRRBRBRBRBBRRRRRRBRRBRBRBRBRRBBRBBRRBBRBRRRRRRRGRBRBRBBBBRRRRBGRBBBGBRRBBBBBRBBRBRRRBBRRRRBRRRBRRBBRBBRBBBRRRBBRRBBRRBGBRRBB
Color predominante: Negro
BRRBBBBBBRBBBBBRRBBRRRBRBRBBBBBBBRBRBBBRBRRBBBBBRRRRRBBBBRBBRRRRBRBRRBBBRRRRBRBRRBBBRRRRBBBRRRBRBRBRRBBRRBRBRBBRRRBRBRRBRRRRBBRRBRBRBRBRRBGBRRRRRRBRBBBRRBBBRBBRRBBRBRBBBGBBRBRRBRBBBRRBBBBRRRRBBRRBBBRBBRBRBBBBBBBBBRBRBRRBBRRRBBRBRRRRBBRRRBBGBBBRRRRBRBBRRRBRBBRRBBBRBRBRRRRBRRRBRRRRBRRRBRBBBRRRRRRRBRBRBRBBRBBRRBGRRBRRRRRRBRBRBBBBBRBBBRRRBBRBBBBRRRBBBBBRRRBBRRBRRRRRBBRBBRBRGBBRRBBBBBBBBBBBBBBRBRRBBRRBBRBBRBRRBBBBBGBBBRRRRRRBBBRBRRBBBBBBBBBRRGBBBBRRBRBRRRRRBRRRBBBBBRBBBRBRRRBRRRBRBRBBBBR
Color predominante: Negro(pero salieron 14 no - negros)
BRBRBBRRRRRBBRBRBRRBRRBRRRBRRBBRRBBBB - RRGRRRRRRRRGRR - BRBBRBRRBRBBBRRRRBBBRBBRBRBRBBGRBBBRRBRBBRRRRRRBGBRRBBBBBBRRRRBBRBBRBBRBRBBRRBBRGBBBBRBRRBRRBRBRBBBRBBRBBBBRRRRRBRRBBBBRBBBBRBRRBBBBBRRBRBBRRGBRRGRBRRBRBRBGRRBRGBBRRBRRR - RBRBRBRBRBRB - BRRBRRRRBBBBBBBRGGRRRBRRRRBBRBRBBRRRBBRRBBBBRBBRBRRBBBRRBBRBBRRBRBBRBRRRRBRBRRBRBBGRRBBGRRGRBRRBRBRRRRRBRBRRBRBRRBBBBRGBBBBBBBRRBBRBRRBBRBRBBBBRRBGRBRBRBBRRRRRBGRRRBBBRBBRRBRRRBBBRBRRBRBBBRBBBRBBBRGBBRBGBBBRBRBRRRBRRGBRRBBRBRRRGBRRGBRRBRRBRBBBBBGBBBBBRRBB



BBBBRRRBBBRBBBBRBRBBRBRRRRRRBRRBBRBBRRBRBBRBBBBBBRBRRBBBBRRRBRRBBRRRBBRRBBRBRRRRBRBBRBBBRRRBRBRRRRBBRBBGBRRRRRRRRRBBRGBBBRBGRBRRBRBBRRBRBBRRRRRBRRRBBBRBRBRRBBBBRRBBRBBRRBBBRRRBBBBRRRBBRRBBBBBRBBBBRBBRRRBBRBRRRBRBBRRBRBBRBRBRRBRBBRRRRBRRRRRBBRBRRRRBRBBRRRRRRRBBRBBBRRRRBBRRRRRBRRRBRBBBRRBRRBRBRRRRBRRRRRRGBBRBBRBRRRBRRBBBRBBBBBBRGBBRBBRRRBRBBRRBBBBRRRRRRBRBBRBRBRRBBRRRRBBRBRBBBBBBBBRBRRBRBBRBRBBBBBRRBRRRRRRRRBRBRBBBRBBBBBBRBRBRBRBBBBBBBRRRRRBBRRBBBBRRRBRRRRBRBRBRBBBRRBRBRBRBBRRRBBRGGRRBRRBBRBRBBBRR
0.5     0.1
1 - 1 - 0.2
2 - 2 - 0.4
3 - 4 - 0.8
4 - 8 - 1.6
5 - 16 - 3.2
6 - 32 - 6.4
7 - 64 - 12.8
8 - 128 - 25.6
9 - 256 - 51.2
10 - 512 - 102.4
11 - 1024 - 204, 8
12 - 2048 - 408, 16

0.5
0.5 - 0.5
0.5 - 0.5 - 1
0.5 - 0.5 - 1 - 1.5
0.5 - 0.5 - 1 - 1.5 - 2

RRGRRRRRRRRGRR


1 - 0.5
2 - 1
3 - 2
4 - 4
5 - 8
6 - 16
7 - 24
8 - 48
9 - 96
10 - 192
11 -


    Si sale alternancia de color: rbr 3, continuar con la alternancia hasta que rompa;